name: 'Approve Test'

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment:
      name: "test-production"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Approve?'