name: 'Approve Test'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'スルーされるはず'


      
  deploy:
    needs: [build]
    environment:
      name: "test-production"

    runs-on: ubuntu-latest

    steps:
      - run: echo 'Approve?'